---

name: MegaLinter

# Trigger mega-linter at every push. Action will also be visible from
# Pull Requests to main
on:
  # Comment this line to trigger action only on pull-requests----------------------------------------------------------------
  # (not recommended if you don't pay for GH Actions)
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_call:

jobs:
    kicad: 
        steps:
            - name: Checkout Repository
                uses: actions/checkout@v6

            - name: Run KiCad actions
                uses: actions-for-kicad/kicad-actions@v2-k10.0
                with:
                schematic_file_name: ./file.kicad_sch
                symbol_libraries: "symbol-library=./symbol-library.kicad_sym"
                run_erc: true
                schematic_output_pdf: true

                pcb_file_name: ./file.kicad_pcb
                footprint_libraries: "footprint-library=./footprint-library.pretty"
                run_drc: true
                pcb_output_gerbers_and_drill: true
                pcb_output_image: true

            - name: Upload schematic
                uses: actions/upload-artifact@v7
                with:
                path: ./schematic.pdf
                archive: false

            - name: Upload gerbers and drill file
                uses: actions/upload-artifact@v7
                with:
                name: Gerbers
                path: ./gerbers

            - name: Upload image render
                uses: actions/upload-artifact@v7
                with:
                path: ./pcb.png
                archive: false